version: '3.8'

services:
  pokemon-api:
    build: ./pokemon-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    container_name: pokemon-api

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pokemon-api
    restart: unless-stopped
    container_name: pokemon-nginx